### ISSUE TITLE
problems with comments

### ISSUE THREAD

**Issue by stephan3321** [Polymaker/ldd-brick-editor#1]
When 1 or more lines of comments are added (i.e. revision management) and the part is re-opened, the complete comments are removed.

**Comment by Polymaker** [comment]
Are you adding the comments within Brick Editor or directly into the primitive xml file?

I was not able to reproduce your problem but I did found some issues handling multiline comments, but none that would explain why the comments were removed all together.

**Comment by Polymaker** [comment]
Oh now I understand what is going on...

When exporting from Brick Studio I add a line in the comments with the last modification date.
When importing from LDD .xml file, the comment is processed line by line (to detect "derived from", "original author", etc.) but if there is a date in the line I assume that it is the last modification date field so only the date is extracted from the line and the remaining text is not kept.

The fix will be ready soon.
