### ISSUE TITLE
[SUGGESTION] Simple decor preview

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#10]
It'd be great if we have some at least simple decor preview ability for decorable parts, cos that checkered A0-X0 style at the moment is basically of no help (hard to tell if the decor would be stretched or some other way deformed).

There could be context menu option after RMB on a decorable brick part be it in canvas or in the right panel for load preview image, after which the image would be stretched across the UV of that part.

**Comment by Polymaker** [comment]
This is a feature I've been wanting to do for a long time.
It is not really a priority right now but I will surely do it at some point.
