### ISSUE TITLE
[SUGGESTION] Keyboard shortcuts

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#12]
I see you have some hard-coded keyboard shortcuts for ONLY SOME options. Why not enable user to defined keyboard shortcut for any option?

For example, I find it pretty annoying/frustrating constantly going to menu and clicking Import 3D file a sit has not keyboard shortcut. It be great if we could define one.

Or is there some hidden option how to do it? Cos I was looking thru the settings/config files but did not find the place where they are defined thus I am thinking they are simply hard-coded into the app, right?

**Comment by Polymaker** [comment]
You are correct the shortcuts are hardcoded.
It is a great idea to have configurable shortcuts but it is not something easy to implement.
I'll keep the idea in mind but I don't think I will add that feature in the near future,
