### ISSUE TITLE
[SUGGESTION] Reversing/exchanging position of left and right panels

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#13]
This is really just a tiny thing: you see, I am JAVA programmer myself working inside the NetBeansIDE and I am just used to have the "tree" on the left side and the actual "object manipulation" part on the right. But we can see this same "logic" in windows itself, and in other win apps too, when there is the tree almost everytime on the left side cos we go from the top to bottom, from left to right, so the selection should/could be on the left as the 1st step...but I admit this is rather non-essential, actually just a wish.

**Comment by Polymaker** [comment]
You can already drag & dock panels and save your custom layout.

**Comment by fafayqa** [comment]
Aha, I did not know that - sorry.
