### ISSUE TITLE
[SUGGESTION] Autogenerated boundings

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#14]
I assume one cannot export the brick (g file) without generating the bounding boxes first, so it would be only logical to be generated automatically right after importing a specific brick part into the project. In such case I do not see need for the generate button anymore: if one want to adjust the values himself he can, of course, but once the bounding is autogenerated there is no expectation to generate it once more manually.

Or OK, there might be reason having those btns present still: if one is editing the values and make some mistake he could still hit the button so the values would be generated once again - in such case I would you to take in consideration renaming those buttons from "Generate" to more accurate "Re-generate"

But still the autogenerated boundings should be added - right?

**Comment by Polymaker** [comment]
I don't think the feature is really needed but it would be easy to add a checkbox in the 3D model import window that would regenerate the bounding if checked.

**Comment by fafayqa** [comment]
Well, what I was thinking is the exact opposite: why there is need for manually generating bounding boxes when they need to be generated anyway, cos without them you cannot export LDD brick? Why we have to manually click special button just to generate them when it can be done by the app as default values when we import 3D? From my programmer's point of view you are simply adding really unnecessary operations for the user.

On the other hand I do  agree, you can add the check box when importing 3D but once again I lack understanding what for would one need model without the bounding boxes - I see no logic behind that, sorry. So now there will be another unnecessary GUI object (checkbox) just to tell app to generate those bounding values the app needs anyway - why not simply autogenerate them without asking? Once again maybe I do not see your concept thoughts, but I cannot see reason why would one need empty bounding values when he needs to generate them anyway sooner or later and yet with the exact default values it can get upon 3D import.

So if you need to generate them anyway why they are not autogenerated right away at the import stage without checkbox to say the app "OK, do it"? To me that has more logic than the actual state (except the cases where one manipulate those values manually, he makes mistakes and want the default values back).

**Comment by Polymaker** [comment]
I have seen many cases in LDD bricks where the bounding box did not match the actual geometry. Most of the time it is only a bit of rounding I assume but sometime there is a considerate difference. Also there is two kinds of bounding boxes and I never figured out what are their exact purpose.

So I chose to not auto generate to allow the user to keep the possibility of entering manual values.
Also in the case you are editing a brick with a "manual" bounding box, then edit the UV in Blender for example and import back, then it would overwrite the original value if I autogenerate the bounding without asking.

The middle ground I think is that when the bounding is empty (all zeroes) then I would autogenerate without asking.

**Comment by fafayqa** [comment]
I do get that but still I do not see anyone - maybe if that person is cyborg or some other type of living machine :-) - going to set those values manually from the scratch just like that: for example, I can only think of it like adjusting the values only after I generated them first with the Generate button, thus still autogenerating the bounding boxes would be reasonable as it would do exactly that, that is the "starting values" one can update himself manually if he want. But how in the world would one know those values otherwise?

Like how you get those values by your own if not via app code? Code can do that easily by computing values we do not see/know just like that by simple looking at the mesh itself - function of the Generate button is the best prove of that...or do we somehow?

How autogenerating the values on import is preventing one to update them manually afterwards if he want? Those values are still editable - exactly what I am talking about whole time, sooo...???

I do not see logic behind that statement/reason, let's summarize it how I understood what you're saying: when you autogenerate those values they are still editable and that is the reason why you chosen not autogenerate to allow the user to keep the possibility of entering manual values...mindboggling, I'm already lost. :-)))

As for the difference between the 2 bounding boxes:

**Bounding** is the area where you can grab the brick (that is: if you move your mouse over brick part that is not within bounding box, it won't let you grab/manipulate the brick at all); this bounding area also has kind-of collision effect - for instance if it is the same as GeometryBounding it will move LDD's floor downward if the brick is placed lower than actual LDD's floor, but if the bounding box is smaller you can really move your brick below LDD's floor and the floor will not be moved (see some of the example pics below)!

**GeometryBounding** is nothing more then the outer box for the brick mesh as whole - a "brick mesh visibility box" for brick list panel on left in LDD (it has no effect for brick visibility in the LDD canvas); it affects what is shown from the brick: if you change it to values that are smaller than the brick dimensions, you start seeing the parts that are outside be not visible at all in the brick list panel on left.

See these examples:

![01](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/3a98c760-b30c-4fde-b891-a8965b803558)
![02](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/3031162c-16dc-4177-8b02-ee921a35c854)
![03](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/c7d434c9-6904-4b46-bac2-a1198f7ef426)
![04](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/06ce937c-6f27-43b6-918a-6a6b6f2784d6)
![05](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/4ea7c854-3bc3-4af2-bfa0-617355648b33)
![06](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/f55c5580-8bf7-449b-b4da-8b0b25c68e40)
![Image 014](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/63729baf-0ff6-4109-b199-868f990a5376)
