### ISSUE TITLE
[SUGGESTION] New icon...maybe? :-)

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#15]
Another rather wish as this is non-essential once again: as I have placed icon of your app right beside the actual LDD icon I am almost all the time clicking the wrong one as they are basically the same! :-)

So what about new icon? Like what I would suggest as your app is creating G files, having it as a small letter "g" (to differentiate it from the ugly Google one) and also at least different hue of blue (in case you still want it to be in blue prolly because of connection to LDD which it has its icon in blue - right?). Maybe creating the small letter g from the bricks in the LDD? It'd be quite original...think about it, please.

**Comment by fafayqa** [comment]
I see you closed this topic without any answer - do I understand it right it annoyed you, or does it mean you already has new icon? It'd be good if you always give some sort of at least one or two word answer.

You see, I do not try to be/sound rude or something, but close it like this does not give me any explanation in what form this was closed (reason), tho I understand it is completely up to you how you manage this section. I guess it would be normal to give reason of some sort.

Or should I try to make one for you, hm? Just tell me icon dimensions and file format (ico/png) you need and I will, no problem, and you will decide if you use them or not (in case that is the case).

**Comment by Polymaker** [comment]
I found your suggestion absurd. The current icon is fine and perfectly represent its purpose: edit LDD bricks. 
It is not like my icon was ugly or pixelated, then I would understand a do-over.

**Comment by fafayqa** [comment]
Ah, so it was the case I thought it was, nevermind - my intention was purely differentiate it visually much more from the LDD icon as they are basically the same, that's all.

BTW I see absolutely nothing absurd about good intended suggestion - why such a harsh word? It was really meant in good heart manner but I see you found it offending as if I was saying it is ugly.

Just to show you how it looks side-by-side with the actual LDD - "He, who find at least 3 differences will win a prize...":

![xxx](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/0aa5fa60-8b03-4f32-9192-684ed9f31f9d)
