### ISSUE TITLE
[SUGGESTION] Change menu option "?" to "Help"

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#17]
I guess the headline tells it all. :-)
This would also allow you in the future to add other submenus to it in case you would have such, as the link to webpage, to updates etc.
This is a standard naming of the menu, I would say, as About is usually under the HELP menu.

And as I am saying this: you could also include some very basic manual for your app, like the basic operations and How-to. That would go exactly under the help menu.

**Comment by Polymaker** [comment]
The only reason I have not named it Help is because there is no help... The app definitively needs some documentation but I haven't had time to work on that. I will rename the menu once there is help available in the app.

**Comment by fafayqa** [comment]
Sure, but you do not need to have any help file to name the last menu option as "Help" - as I said I saw it too many times. It basically is naming menu standard (if there is anything like that at all as "menu naming standard").

Or you can simply call it "About" - there would not be another unnecessary "About" value under/inside it, rather it would immediately open the small about window - it is up to you, both cases are OK.
