### ISSUE TITLE
[SUGGESTION]{+pic} Direct LDD brick to 3D export

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#18]
Why we need to first load a brick to be able exporting it to 3D if that is really all we want?

I suggest you to add new menu option under TOOLS which could be called "Direct brick to 3D export", which could re-use already existing table/list of LDD bricks you are using for "Import from LDD", that is this one here:
![Image 001](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/d48e2a4e-5f53-4063-94e8-a3d174a3f5bd)

That would simply directly export selected LDD bricks in that table/list and export it to the location defined in the "Output files in" without loading the brick to the app canvas as there is no need for that cos we only wanted to export it as 3D file to be able edit it in some external 3D editor like Blender.

And, of course, such exported brick should consist of all the different .g files the brick has, creating one single model, where each individual .g segment would be separate 3D object once opened in 3D editor like Blender (but I think you already have this specific "thing" implemented if I remember correctly, right?).

Also I would say that when you exporting LDD brick to 3D file you need to export just the brick omitting any camera and light - what for? There is no camera nor light in that brick, just the mesh itself. If one want to have camera and light added to the mesh inside the 3D editor, he can do it still by himself.

But still, if one would be exporting brick from the canvas, that is after some editing in your app (if editing is even possible there) then you could add also camera cos it would have its logic then (not light, as there is none in the canvas - do not try to be more Pope than Pope himself, as saying goes in my country, LOL).

**Comment by Polymaker** [comment]
In the export window, there is an option to export a brick directly from LDD.
Just click on the button next to "Select part" or enter the part number manually.
![image](https://github.com/Polymaker/ldd-brick-editor/assets/6391719/38d52f5e-4047-4487-93e5-806378715bdf)

**Comment by Polymaker** [comment]
Also the exported model does not contains camera or lights. 
Are you confusing the default light and camera present in blender? When importing an obj or dae the scene is not cleared.

**Comment by fafayqa** [comment]
Good that this option is already there, but still: wouldn't it be better to have dynamic roll menu with autogenerated g files checked by app for the specific brick instead of letting user to type it himself? You/we would avoid situation where one do not know what part brick has or cases where one would type non-existent g part of the brick.

As for the camera and light "issue": In fact I never realized that when one is importing dae into the Blender it autogenerates camera and light. But now as I think about it knowing dae AWLAYS contain camera and light values, you are prolly right - sorry for that part.

**Comment by fafayqa** [comment]
Good it already is there, but wouldn't it be better to have dynamic roll menu with autogenerated g files checked by app for the specific brick instead of letting user to type it himself? You/we would avoid situation where one do not know what part brick has or cases where one would type non-existent g part of the brick.
