### ISSUE TITLE
[SUGGESTION] Visually differentiate between editable values and label texts

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#19]
I am somewhat baffled by the fact you have editable values texts and label texts (read only) in the exact same visual style that is further messing things up as it is not clear right away something is editable and other is not.

What I would suggest here would be changing to color of label texts to some more light color resembling some other already used GUI colors, for example color of the GUI object borders or something, simply not having it in the very exact color as editable texts (values). I would even think about additional bolding of the label texts, where editable values would remain in normal font weight.

Of course, editable values text would remain as they are, that is black text color on white background.

**Comment by Polymaker** [comment]
Can you please tell me which labels are displayed as textboxes?
I can't find anything that match your description.

**Comment by fafayqa** [comment]
We do not understand here: I am not saying labels are displayed as editable texts, I am saying for better differentiating and less visual "clogging" it might be good/better to differentiate labels from editable texts by different font color and size/weight, cos now when one look at the actual GUI design all looks the same. It should be immediately known just by look what is label and what is editable text as now all use exactly the same font style. That is all I wanted to say/suggest.

This is what I meant, something like these two examples here (just some quick ideas I used as examples in my other suggestions for your app elsewhere so you might already see them):
![a](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/36b279cf-5eab-4587-9f02-609411d8d49d)
![Image 002](https://github.com/Polymaker/ldd-brick-editor/assets/26612946/5f7f5794-19be-4daf-ad5d-e2c741b7591f)
