### ISSUE TITLE
Unexpected error on start

### ISSUE THREAD

**Issue by cantabrigia** [Polymaker/ldd-brick-editor#2]
When starting 1.0.8.0 (x86 or x64, on Win7), the following error occurs:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at LDD.BrickEditor.Settings.SettingsManager.ValidateLddPaths()
   at LDD.BrickEditor.UI.Windows.BrickEditorWindow.InitializeAfterShown()
   at LDD.BrickEditor.UI.Windows.BrickEditorWindow.<OnInitializationPopupLoaded>b__67_0()`

and application sits around with "Initializing Resources", apparently doing nothing (I've left it for more than an hour, at least).

**Comment by Polymaker** [comment]
Thanks for notifying me. I will investigate what might be the issue. In the meantime, can I ask you if you have Lego digital designer installed and on what drive? The error comes from a piece of code that tries to detect where LDD is installed but in theory it should not crash even if it is not installed.

**Comment by cantabrigia** [comment]
> Thanks for notifying me. I will investigate what might be the issue. In the meantime, can I ask you if you have Lego digital designer installed and on what drive? The error comes from a piece of code that tries to detect where LDD is installed but in theory it should not crash even if it is not installed.

LDD install directory is `C:\Program Files (x86)\Lego Digital Designer`

I did notice that `settings.json` had null for both application paths (even the LDD appdata path, which as far as I know is default), but plugging the paths in there manually resulted in the same error (possible that I got the syntax wrong, though).

**Comment by Polymaker** [comment]
Would you mind sending me your settings.json file so I can have a look at it?
You can attach the file in a comment.

**Comment by cantabrigia** [comment]
settings.json, as ordered. Installed 1.0.8.0 x64, started it up, got the error, copied the file, so this is exactly as-created.
[settings.zip](https://github.com/Polymaker/ldd-brick-editor/files/10864315/settings.zip)

**Comment by Polymaker** [comment]
I was able to reproduce the issue. It should be a quick fix and I will make a new release in the following days.

**Comment by Polymaker** [comment]
Sorry for the delay I was pretty busy. I have just released an update that should fix the issue.
