### ISSUE TITLE
[SUGGESTION] simple UV manipulation - could this be done?

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#22]
I am not sure if this can be done in your app outside the actual 3D editor like Blender, but could you implement some simple UV manipulation similar to mesh manipulation, like changing of its position, size and rotation?

Reason: I quite often find the UV being slightly (well, sometime quite a lot) out of the correct position/size/rotation and it is a bit bothering to go zillions of time back and forward between your app and my 3D editor just to re-adjust UV - this way it was be great enhancement to the workflow of this whole LDD brick creation!

**Comment by Polymaker** [comment]
Well it could be done, but my app is not focused around 3D editing. It would take a considerate amount of time to implement and I have other priorities (both IRL and features to implement)

**Comment by fafayqa** [comment]
Have no clue what IRL is...Google did not helped me either.
Indie Racing League, In real Life...just a few Google results for IRL I guess are definitely not the ones you are talking about, right? :-)

**Comment by Polymaker** [comment]
IRL is short for In Real Life, meaning outside of gaming or computer stuff,
My wife gave birth to our son two weeks ago so I'm a little busy to say the least.

**Comment by fafayqa** [comment]
Oh, that's superb, you're a lucky man - all the best to both of you, ehm, I mean to all three of you, of course!!!
