### ISSUE TITLE
[BUG] Merge meshes not working

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#25]
I am not sure if I understood this correctly, but I suppose that when I select all the individual brick parts in app canvas, and chose canvas menu "Mesh > Merge meshes", they should actually visually merge into one object replacing all the individual parts on canvas and also in the Project Tree under its Elements section in the Navigation panel, right?

If this should be the case, then there is a problem/bug, as absolutely nothing happens - there are still all the separate parts and no new one (merged) is created.

Or am I doing something wrong?

**Comment by Polymaker** [comment]
You may doing something wrong but in your defence the app lacks documentation 😅
I suspect that what you are trying to merge is sub-elements of the brick:
![image](https://github.com/Polymaker/ldd-brick-editor/assets/6391719/79525ca4-d91f-47db-b13c-e8e482100224)
These do not only represent a mesh but also have some data and values in the G file.
The function can merge meshes in the same "brick sub-element" like this:
![image](https://github.com/Polymaker/ldd-brick-editor/assets/6391719/bd9268f3-52a9-466e-804c-0e26f094c75f)

But it is actually possible to merge all by doing some manual work before. If you expand each sub-element, you can drag each mesh in the main sub-element (called PartX where X is a number). Then you can select them and merge and you can delete the empty sub-elements.
![image](https://github.com/Polymaker/ldd-brick-editor/assets/6391719/15a05abb-a531-4c34-8358-d3d3710c0c7d)
