### ISSUE TITLE
[SUGGESTION] Brick outline mesh/edges 3D file

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#5]
What about adding specific 3D files that would contain basically just the edges of the supposed outlines we created ourselves to avoid situation where you app cannot generate them or even crashes when trying to, hm?

I guess this would even make the process quicker than to wait for the app process and logic to generate those.

One would simply RMB somewhere in the canvas or the right panel and there would be new context option something like "add Outline Edges 3D mesh": once clicked we could provide our outline edges 3D file (dae/obj) which would be basically just a vertexes and edges with no faces and that would be src for creating outline edges on the brick once in LDD. This of course wouldn't mean that the actual option to generate outlines would disappear, no, it would only further expand option to create them in scenario I described above.  It would also enable user to define exactly what he thinks should be highlighted as the outline edges of the specific brick. Once added it should become grayed out in the context menu until it is removed form the brick, of course.

I think to implement this would be really easy, wouldn't it?

**Comment by Polymaker** [comment]
It's a good idea and I remember trying to implement something like this but if I remember correctly obj and dae files do not support edge only models, when exporting a mesh with only edges in blender it would create empty obj or dae files.

**Comment by fafayqa** [comment]
Well, they do - most definitely obj does, as I tested it. I created test cube (the default one created when you open new general project in Blender, newest 3.6.4): I triangulated faces first, then deleted all the cross-edges so only the cube frame was left. I exported this as obj file. Then I imported the file into Blender: I get the cube frame! ;-)

This is the content of such obj file:

```
# Blender v3.6.4 OBJ File: ''
# www.blender.org
mtllib untitled.mtl
v 1.000000 1.000000 -1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 1.000000
l 6 8
l 2 6
l 1 2
l 8 7
l 3 4
l 5 6
l 3 7
l 1 3
l 8 4
l 7 5
l 5 1
l 4 2
```

**Comment by Polymaker** [comment]
Ok thanks for the info. I am planning to rework the outlines generation part of the application. I want to give more control over the detection of "hard" edges and also save those edges in the project file instead of recalculating them each time. So this opens up the possibility to manually specify which edges to outlines.

I don't have a lot of free time and this is not my priorities but I will definitively keep the idea in mind.
